apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data-pvc
      containers:
      - name: minecraft-server
        image: itzg/minecraft-bedrock-server:latest
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
          requests:
            memory: {{ .Values.resources.requests.memory }}
        env:
          - name:  EULA
            value: 'TRUE'
          - name: MODE
            value: {{ .Values.minecraft.gamemode }}
          - name: MOTD
            value: {{ .Values.minecraft.motd }}
          - name: ALLOW_FLIGHT
            value: 'TRUE'
        ports:
        - containerPort: {{ .Values.minecraft.port }}
          protocol: UDP
          name: minecraft
        volumeMounts:
          - name: minecraft-data
            mountPath:  /data
        readinessProbe:
          exec:
            command:
            - mc-monitor
            - status-bedrock
          initialDelaySeconds: 30
          periodSeconds: 30
        livenessProbe:
          exec:
            command:
            - mc-monitor
            - status-bedrock
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: minecraft-server
  ports:
  - protocol:  {{ .Values.minecraft.protocol }}
    port: {{ .Values.minecraft.port }}
    targetPort: {{ .Values.minecraft.port }}
    nodePort: {{ .Values.minecraft.nodeport }}

